FROM ghcr.io/danny-avila/librechat-dev@sha256:8fce2f8fa48a7cc12285e1acbc2e28c1583348b260dfadfbec33b1d7a4dab0d1
COPY api/server/sendEmail.js /app/api/server/utils/sendEmail.js
# --- Fix: ensure email templates exist ---
COPY api/server/utils/emails /app/api/server/emails
